# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schemas/protobuf_all_datatypes.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'schemas/protobuf_all_datatypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$schemas/protobuf_all_datatypes.proto\x12\x06sample\"\x8f\x06\n\rSampleMessage\x12\x15\n\rboolean_field\x18\x01 \x01(\x08\x12\x13\n\x0bint32_field\x18\x02 \x01(\x05\x12\x13\n\x0bint64_field\x18\x03 \x01(\x03\x12\x14\n\x0cuint32_field\x18\x04 \x01(\r\x12\x14\n\x0cuint64_field\x18\x05 \x01(\x04\x12\x14\n\x0csint32_field\x18\x06 \x01(\x11\x12\x14\n\x0csint64_field\x18\x07 \x01(\x12\x12\x15\n\rfixed32_field\x18\x08 \x01(\x07\x12\x15\n\rfixed64_field\x18\t \x01(\x06\x12\x16\n\x0esfixed32_field\x18\n \x01(\x0f\x12\x16\n\x0esfixed64_field\x18\x0b \x01(\x10\x12\x13\n\x0b\x66loat_field\x18\x0c \x01(\x02\x12\x14\n\x0c\x64ouble_field\x18\r \x01(\x01\x12\x13\n\x0b\x62ytes_field\x18\x0e \x01(\x0c\x12\x14\n\x0cstring_field\x18\x0f \x01(\t\x12\x32\n\nenum_field\x18\x10 \x01(\x0e\x32\x1e.sample.SampleMessage.EnumType\x12\x41\n\x14nested_message_field\x18\x11 \x01(\x0b\x32#.sample.SampleMessage.NestedMessage\x12\x1e\n\x16repeated_boolean_field\x18\x12 \x03(\x08\x12\x36\n\tmap_field\x18\x13 \x03(\x0b\x32#.sample.SampleMessage.MapFieldEntry\x12\x1b\n\x11oneof_int32_field\x18\x14 \x01(\x05H\x00\x12\x1c\n\x12oneof_string_field\x18\x15 \x01(\tH\x00\x1a+\n\rNestedMessage\x12\x1a\n\x12nested_int32_field\x18\x01 \x01(\x05\x1a/\n\rMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\":\n\x08\x45numType\x12\x0e\n\nENUM_TYPE1\x10\x00\x12\x0e\n\nENUM_TYPE2\x10\x01\x12\x0e\n\nENUM_TYPE3\x10\x02\x42\r\n\x0boneof_fieldb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schemas.protobuf_all_datatypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLEMESSAGE_MAPFIELDENTRY']._loaded_options = None
  _globals['_SAMPLEMESSAGE_MAPFIELDENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLEMESSAGE']._serialized_start=49
  _globals['_SAMPLEMESSAGE']._serialized_end=832
  _globals['_SAMPLEMESSAGE_NESTEDMESSAGE']._serialized_start=665
  _globals['_SAMPLEMESSAGE_NESTEDMESSAGE']._serialized_end=708
  _globals['_SAMPLEMESSAGE_MAPFIELDENTRY']._serialized_start=710
  _globals['_SAMPLEMESSAGE_MAPFIELDENTRY']._serialized_end=757
  _globals['_SAMPLEMESSAGE_ENUMTYPE']._serialized_start=759
  _globals['_SAMPLEMESSAGE_ENUMTYPE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
